In the first program, x prints 3. Since x was assigned in the outer scope
it is available to be changed in the inner scope. 

In the second program, there is an error. Since x was first assigned in 
the inner scope it is not available in the outer scope.